allowed_characters:
  - '0032' # ' '
  - '0033-34' # ! "
  - '0039-41' # ' ( )
  - '0044-0063' # , - . / 0-9 : ; < = > ?
  - '0091' # [
  - '0093' # ]
  - '4608-4991' # Ethiopic range
  - '8211' # –
  - '8212' # —