allowed_characters:
  - '0032' # ' '
  - '0033-34' # ! "
  - '0039-41' # ' ( )
  - '0044-0063' # , - . / 0-9 : ; < = > ?
  - '0091' # [
  - '0093' # ]
  - '1536-1791' # Arabic range
  - '8206-8207' # Left-to-right and Right-to-left Mark
  - '8211' # –
  - '8212' # —