allowed_characters:
  - '0032' # ' '
  - '0033-41' # ! " # $ % & ' ( )
  - '0044-0059' # , - . / 0-9 : ;
  - '0063' # ?
  - '0064' # @ //remove?
  - '0091' # [
  - '0093' # ]
  - '1040-1066' # А-Ъ
  - '1068' # Ь
  - '1070-1071' # Ю-Я
  - '1072-1098' # а-ъ
  - '1100' # ь
  - '1102-1103' # ю-я
  - '1117' # ѝ
  - '8211' # en dash
  - '8212' # em dash

normalize_characters:
  '8230': '' # Remove ellipsis
  '0182': '' # Remove ¶
  '1104': '1077' # replace ѐ with е
  '8208': '0045' # Change HYPHEN to HYPHEN-MINUS
  '8210': '0045' # Change FIGURE DASH to HYPHEN-MINUS
  '8722': '0045' # Change MINUS SIGN to HYPHEN-MINUS
  '8260': '0047' # Replace fraction slash with forward slash
  # Replace latin equivalents with Cyrillic
  '0065': '1040' # A
  '0069': '1045' # E
  '0079': '1054' # O
  '0097': '1072' # a
  '0101': '1077' # e
  '0111': '1086' # o

use_edit_distance: true
