allowed_characters:
  - '0032' # ' '
  - '0033-35' # ! " #
  - '0037-41' # % & ' ( )
  - '0044-0062' # , - . / 0-9 : ; < = >
  - '0063-0122' # ? @ A-Z a-z
  - '0225' # á
  - '0233' # é
  - '8211' # –
  - '8212' # —