allowed_characters:
  - '0032' # ' '
  - '0033-41' # ! " # $ % & ' ( )
  - '0044-0062' # , - . / 0-9 : ; < = >
  - '0063-0122' # ? @ A-Z [ ] _ a-z
  - '0197-198' # Å Æ
  - '0201' # É
  - '0205' # Í
  - '0216' # Ø
  - '0229-230' # å æ 
  - '0233' # é
  - '0237' # í 
  - '0248' # ø
  - '8211' # –
  - '8212' # —