allowed_characters:
  - '0032' # ' '
  - '0033-0034' # ! "
  - '0039-0041' # ' ( )
  - '0044-0046' # , - .
  - '0048-0059' # 0-9 : ;
  - '0063' # ?
  - '0065-0080' # A-P
  - '0082-0087' # R-W
  - '0089-0090' # Y-Z
  - '0097-0112' # a-p
  - '0114-0119' # r-w
  - '0121-0122' # y-z
  - '0200' # E with grave
  - '0232' # e with grave
  - '0210' # O with grave
  - '0242' # o with grave
  - '0091' # [
  - '0093' # ]
  - '8211' # en dash
  - '8212' # em dash

normalize_characters:
  '8230': '' # Remove ellipsis
  '0182': '' # Remove ¶
  '8208': '0045' # Change HYPHEN to HYPHEN-MINUS
  '8210': '0045' # Change FIGURE DASH to HYPHEN-MINUS
  '8722': '0045' # Change MINUS SIGN to HYPHEN-MINUS
  '8260': '0047' # Replace fraction slash with forward slash

  '0233': '0232' # e with acute to e with grave
  '0243': '0242' # o with acute to o with grave

use_edit_distance: true
