allowed_characters:
  - '0032' # ' '
  - '0033-34' # ! "
  - '0039-41' # ' ( )
  - '0044-0063' # , - . / 0-9 : ; < = > ?
  - '0091' # [
  - '0093' # ]
  - '0095-96' # _ `
  - '0171' # «
  - '0187' # »
  - '1329-1423' # Armenian Range
  - '8211' # –
  - '8212' # —
  - '8228' # ․ mijaket