# Japanese 
CJK: True

longest_word_length: 100
character_frequency_cutoff: 0.0001
# use_edit_distance: True

normalize_characters:
  '8230': '' # Remove ellipsis
  '8226': '' # Remove bullet •
  '9702': '' # Remove White bullet ◦
  '0182': '' # Remove ¶
  '0042': '' # Remove *
  '0180': '0039' # replace ´ with '
  '8260': '0047' # Replace fraction slash with forward slash
  '0169': '' # Remove ©
  '12302': '12300'  # 『  -> 「
  '12303': '12300'  # 』-> 」
  '44' : '12289' # , -> 、

remove_regex_patterns:
- '神のプロセス - 神に召された預言者'

