allowed_characters:
  - '0032' # ' '
  - '0033-41' # ! " # $ % & ' ( )
  - '0044-0062' # , - . / 0-9 : ; < = >
  - '0063-0122' # ? @ A-Z a-z
  - '0192' # À
  - '0224' # à
  - '0248' # ø (at least in foreign words)
  - '0249' # ù
  - '0250' # ú
  - '0252' # ü
  - '0296-0299' # Ĩ ĩ Ī ī
  - '0360-0361' # Ũ ũ
  - '0463-0464' # Ǐ ǐ
  - '0534-0535' # Ȗ ȗ
  - '7749' # ṅ
  - '7865' # ẹ
  - '7885' # ọ
  - '8054' # ὶ
  - '8160' # ῠ
  - '8211' # –
  - '8212' # —