word_initial_delimiter: "(?:(?<=[\u0E80-\u0EFF\u200B ])|(?<=^))"
word_final_delimiter: "(?:(?=[\u0E80-\u0EFF\u200B ])|(?=$))"

allowed_spaces:
  - "\u0020" # ascii space
  - "\u200B" # Zero-width space

replacement_space: "\u200B" # Zero width space

allowed_characters:
 - '0032' # ' '
 - '0033-0041' # ! " # $ % & ' ( ) 
 - '0044-0062' # , - . / 0-9 : ; < = >
 - '0063' # ?
 - '0091' # [
 - '0093' # ]
 - '0095' # _
 - '0171' # «
 - '0187' # »
 - '3713-3807' # Lao unicode range ກ - ໟ
 - '8203' # Zero-width Space
 - '8208' # ‐
 - '8211-8212' # – —

remove_long_words: False