allowed_characters:
  - '0032' # ' '
  - '0033-0035' # ! " #
  - '0037-0041' # % & ' ( )
  - '0044-0059' # , - . / 0-9 : ;
  - '0063' # ?
  - '0064' # @ //remove?
  - '0091' # [
  - '0093' # ]
  - '1027' # Ѓ
  - '1029' # Ѕ
  - '1032-1034' # Ј Љ Њ
  - '1036' # Ќ
  - '1039' # Џ
  - '1040-1048' # А-И
  - '1050-1064' # К-Ъ
  - '1072-1080' # а-и
  - '1082-1096' # к-ш
  - '1107' # ѓ
  - '1109' # ѕ
  - '1112-1114' # ј љ њ
  - '1116' # ќ
  - '1117' # ѝ
  - '1119' # џ
  - '8211' # en dash
  - '8212' # em dash

normalize_characters:
  '8230': '' # Remove ellipsis
  '0182': '' # Remove ¶
  '1104': '1077' # replace ѐ with е
  '8208': '0045' # Change HYPHEN to HYPHEN-MINUS
  '8210': '0045' # Change FIGURE DASH to HYPHEN-MINUS
  '8722': '0045' # Change MINUS SIGN to HYPHEN-MINUS
  '8260': '0047' # Replace fraction slash with forward slash
  # Replace latin equivalents with Cyrillic
  '0065': '1040' # A
  '0069': '1045' # E
  '0079': '1054' # O
  '0097': '1072' # a
  '0101': '1077' # e
  '0111': '1086' # o

use_edit_distance: true
