# Config file for Portuguese (Brazilian)
use_edit_distance: True

remove_regex_patterns:
- '%@|@@'
- 'org\.ldschurch'
- '(Bpt|Ph|Ept)@'
- '%\d\$\w'
- '%s'
- '%\w'

allowed_characters:
- '32' # SPACE            
- '33' # EXCLAMATION MARK 
- '34' # QUOTATION MARK   
- '35' # NUMBER SIGN      
- '36' # DOLLAR SIGN      
- '37' # PERCENT SIGN     
- '38' # AMPERSAND        
- '39' # APOSTROPHE       
- '40' # LEFT PARENTHESIS 
- '41' # RIGHT PARENTHESIS
- '43' # PLUS SIGN        
- '44' # COMMA            
- '45' # HYPHEN-MINUS     
- '46' # FULL STOP        
- '47' # SOLIDUS          
- '48' # DIGIT ZERO       
- '49' # DIGIT ONE        
- '50' # DIGIT TWO        
- '51' # DIGIT THREE      
- '52' # DIGIT FOUR       
- '53' # DIGIT FIVE       
- '54' # DIGIT SIX        
- '55' # DIGIT SEVEN      
- '56' # DIGIT EIGHT      
- '57' # DIGIT NINE       
- '58' # COLON            
- '59' # SEMICOLON        
- '61' # EQUALS SIGN           
- '63' # QUESTION MARK         
- '64' # COMMERCIAL AT         
- '65' # LATIN CAPITAL LETTER A
- '66' # LATIN CAPITAL LETTER B
- '67' # LATIN CAPITAL LETTER C
- '68' # LATIN CAPITAL LETTER D
- '69' # LATIN CAPITAL LETTER E
- '70' # LATIN CAPITAL LETTER F
- '71' # LATIN CAPITAL LETTER G
- '72' # LATIN CAPITAL LETTER H
- '73' # LATIN CAPITAL LETTER I
- '74' # LATIN CAPITAL LETTER J
- '75' # LATIN CAPITAL LETTER K
- '76' # LATIN CAPITAL LETTER L
- '77' # LATIN CAPITAL LETTER M
- '78' # LATIN CAPITAL LETTER N
- '79' # LATIN CAPITAL LETTER O
- '80' # LATIN CAPITAL LETTER P
- '81' # LATIN CAPITAL LETTER Q
- '82' # LATIN CAPITAL LETTER R
- '83' # LATIN CAPITAL LETTER S
- '84' # LATIN CAPITAL LETTER T
- '85' # LATIN CAPITAL LETTER U
- '86' # LATIN CAPITAL LETTER V
- '87' # LATIN CAPITAL LETTER W
- '88' # LATIN CAPITAL LETTER X
- '89' # LATIN CAPITAL LETTER Y
- '90' # LATIN CAPITAL LETTER Z
- '91' # LEFT SQUARE BRACKET   
- '93' # RIGHT SQUARE BRACKET  
- '95' # LOW LINE              
- '97' # LATIN SMALL LETTER A  
- '98' # LATIN SMALL LETTER B  
- '99' # LATIN SMALL LETTER C  
- '100' # LATIN SMALL LETTER D  
- '101' # LATIN SMALL LETTER E  
- '102' # LATIN SMALL LETTER F  
- '103' # LATIN SMALL LETTER G  
- '104' # LATIN SMALL LETTER H  
- '105' # LATIN SMALL LETTER I  
- '106' # LATIN SMALL LETTER J  
- '107' # LATIN SMALL LETTER K  
- '108' # LATIN SMALL LETTER L  
- '109' # LATIN SMALL LETTER M  
- '110' # LATIN SMALL LETTER N  
- '111' # LATIN SMALL LETTER O  
- '112' # LATIN SMALL LETTER P  
- '113' # LATIN SMALL LETTER Q  
- '114' # LATIN SMALL LETTER R  
- '115' # LATIN SMALL LETTER S  
- '116' # LATIN SMALL LETTER T  
- '117' # LATIN SMALL LETTER U  
- '118' # LATIN SMALL LETTER V  
- '119' # LATIN SMALL LETTER W  
- '120' # LATIN SMALL LETTER X  
- '121' # LATIN SMALL LETTER Y  
- '122' # LATIN SMALL LETTER Z  
- '123' # LEFT CURLY BRACKET    
- '124' # VERTICAL LINE         
- '125' # RIGHT CURLY BRACKET   
- '126' # TILDE                 
- '192' # LATIN CAPITAL LETTER A WITH GRAVE     
- '193' # LATIN CAPITAL LETTER A WITH ACUTE     
- '194' # LATIN CAPITAL LETTER A WITH CIRCUMFLEX
- '195' # LATIN CAPITAL LETTER A WITH TILDE     
- '199' # LATIN CAPITAL LETTER C WITH CEDILLA   
- '200' # LATIN CAPITAL LETTER E WITH GRAVE     
- '201' # LATIN CAPITAL LETTER E WITH ACUTE     
- '202' # LATIN CAPITAL LETTER E WITH CIRCUMFLEX
- '205' # LATIN CAPITAL LETTER I WITH ACUTE     
- '206' # LATIN CAPITAL LETTER I WITH CIRCUMFLEX
- '211' # LATIN CAPITAL LETTER O WITH ACUTE     
- '212' # LATIN CAPITAL LETTER O WITH CIRCUMFLEX
- '213' # LATIN CAPITAL LETTER O WITH TILDE     
- '218' # LATIN CAPITAL LETTER U WITH ACUTE
- '224' # LATIN SMALL LETTER A WITH GRAVE     
- '225' # LATIN SMALL LETTER A WITH ACUTE     
- '226' # LATIN SMALL LETTER A WITH CIRCUMFLEX
- '227' # LATIN SMALL LETTER A WITH TILDE     
- '231' # LATIN SMALL LETTER C WITH CEDILLA   
- '232' # LATIN SMALL LETTER E WITH GRAVE     
- '233' # LATIN SMALL LETTER E WITH ACUTE     
- '234' # LATIN SMALL LETTER E WITH CIRCUMFLEX
- '236' # LATIN SMALL LETTER I WITH GRAVE     
- '237' # LATIN SMALL LETTER I WITH ACUTE     
- '238' # LATIN SMALL LETTER I WITH CIRCUMFLEX
- '242' # LATIN SMALL LETTER O WITH GRAVE     
- '243' # LATIN SMALL LETTER O WITH ACUTE     
- '244' # LATIN SMALL LETTER O WITH CIRCUMFLEX
- '245' # LATIN SMALL LETTER O WITH TILDE    
- '249' # LATIN SMALL LETTER U WITH GRAVE     
- '250' # LATIN SMALL LETTER U WITH ACUTE     
- '251' # LATIN SMALL LETTER U WITH CIRCUMFLEX
- '8211' # EN DASH
- '8212' # EM DASH