# config file for Slovak

use_edit_distance: True

allowed_characters:
  - '32' # space
  - '33-41' # 
  - '44-59' # , - . / 0-9 : ;
  - '63' # question mark
  - '65-90' # capital latin
  - '91' # [
  - '93' # ]
  - '95' # _
  - '97-122' # lowercase latin
  - '124' # |
  - '193' # Á
  - '196' # Ä
  - '201' # É
  - '205' # Í
  - '211' # Ó
  - '212' # Ô
  - '218' # Ú
  - '221' # Ý
  - '225' # á
  - '228' # ä
  - '233' # é
  - '237' # í
  - '243' # ó
  - '244' # ô
  - '250' # ú
  - '253' # ý
  - '268' # Č
  - '269' # č
  - '270' # Ď
  - '271' # ď
  - '314' # ĺ
  - '317' # Ľ
  - '318' # ľ
  - '327' # Ň
  - '328' # ň
  - '352' # Š
  - '353' # š
  - '356' # Ť
  - '357' # ť
  - '381' # Ž
  - '382' # ž
  - '8211' # en dash
  - '8212' # em dash