allowed_characters:
  - '0032' # ' '
  - '0033-0036' # ! " # $
  - '0037-0041' # % & ' ( )
  - '0044-0059' # , - . / 0-9 : ;
  - '0063' # ?
  - '0065-0122' # A-z
  - '8211' # en dash
  - '8212' # em dash