normalize_regex_patterns:
  '\\!': '!'
  '\\:': ':'
  '\\n': ' '
  '\\t': ' '
  # '(?<=[^\s–\-—\/\-,:#$%]\b)(?<!\d\.)(\d+)$': '' # Remove footnotes
  '^! ': '' # Remove ! with a space at the beginning of a segment
  '^!': '' # Remove any ! at the beginning of a segment
  '^\. ': '' # Remove any full stop at the beginning of a segment if there is a space after
  '^#+': '' # Remove one or more # at the beginning of a segment
  '^- #+': '' # Remove - ## or - ### at the beginning of a segment
  '^–+': '' # Remove one or more – at the beginning of a sentence
  '^—+': '' # Remove one or more — at the beginning of a sentences
  '^-+': '' # Remove one or more - at the beginning of a sentence
  '__+': '_' #Turn contiguous underline characters into a single underline.
  # Need two of these because the positive lookbehinds are fixed-width.
  '(?<=^\d)\.(?=[a-zA-Z])': '. ' # Convert a bullet number with no space to one with a space (ex: 14.hello -> 14. hello)
  '(?<=^\d\d)\.(?=[a-zA-Z])': '. ' # Convert a bullet number with no space to one with a space (ex: 14.hello -> 14. hello)
  '^\d+–\d+, ': '' # Remove starting verse ranges (eg. 7–8, He is in the midst of His Saints, who will soon see Him; -> He is in the midst of His Saints, who will soon see Him;)
  '^_ ': '' # Remove a leading underscore and space if it occurs.
  '^\d+(?=[A-Za-z])': '' # Remove the verse number when it occurs
  '(?<=^)_(?=\w)|(?<= )_(?=\w)|(?<=\w)_(?=$)|(?<=\w)_(?= )': '' # Remove any beginning or ending _ directly next to a word (i.e. _this_ or _this or this_)
  '′′': '"'
  '′': "'"

  